// <auto-generated />
using APISecurity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APISecurity.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250903011816_addedEmp")]
    partial class addedEmp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APISecurity.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "Index_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("APISecurity.Models.ClientKeyIV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ClientKeyIVs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "DefaultClient",
                            IV = "/X9EAc4vBALd31ye7N3L1g==",
                            Key = "Yyj9nVLtBLwPANTqZNFHrofcH/AbvJlaUbytoHT8Qd8="
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "Client1",
                            IV = "Qb4nTgWS7UBo2YU7G/gJCg==",
                            Key = "gi1D2eDd8Tg565ZbfRWc00j9xKtBka4ZHu0Sen+Drgc="
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "Client2",
                            IV = "3Y/S5SC3qFNaSbfSKEKxxA==",
                            Key = "mPjeDLj4jq5AnX/0WeDXBewm05AIOqbV83MfNTWap7A="
                        },
                        new
                        {
                            Id = 4,
                            ClientId = "Client3",
                            IV = "8PiYfRaj4e5JumnpLh0FzA==",
                            Key = "J0N55pEAha+B0Oyggc4zWV1GE9iWiW/m7W5DuUo0W3M="
                        });
                });

            modelBuilder.Entity("APISecurity.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice Smith",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob Johnson",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carol White",
                            Salary = 55000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
